blank_issues_enabled: false
contact_links:
  - name: Sourcehut Issue Tracker
    url: https://todo.sr.ht/~the-commits/tjenamors-se-unattended-upgrades
    about: Please report issues on sourcehut, not GitHub.
