---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: ubuntu-2404
    box: generic/ubuntu2404
    box_version: "4.3.12"
    cpus: 1
    memory: 1024
    driver:
      video_type: none
      graphics_type: none
    synced_folders: []
provisioner:
  name: ansible
  ansible_args:
    - --roles-path=$MOLECULE_PROJECT_DIRECTORY/../..
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
    - idempotence
    - verify
    - destroy
